/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Usuarios
         * @description Lista usuários com paginação.
         */
        get: operations["listar_usuarios_users__get"];
        put?: never;
        /**
         * Criar Usuario
         * @description Cria um novo usuário (discipulador).
         */
        post: operations["criar_usuario_users__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter Usuario
         * @description Obtém um usuário pelo ID.
         */
        get: operations["obter_usuario_users__user_id__get"];
        /**
         * Atualizar Usuario
         * @description Atualiza um usuário.
         */
        put: operations["atualizar_usuario_users__user_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/convertidos-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Contar Convertidos Discipulador
         * @description Conta quantos novos convertidos estão vinculados a um discipulador.
         */
        get: operations["contar_convertidos_discipulador_users__user_id__convertidos_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novos-convertidos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Novos Convertidos
         * @description Lista novos convertidos com paginação.
         */
        get: operations["listar_novos_convertidos_novos_convertidos__get"];
        put?: never;
        /**
         * Criar Novo Convertido
         * @description Cria um novo convertido.
         */
        post: operations["criar_novo_convertido_novos_convertidos__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novos-convertidos/com-cep/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Criar Novo Convertido Com Cep
         * @description Cria um novo convertido preenchendo endereço automaticamente via CEP.
         */
        post: operations["criar_novo_convertido_com_cep_novos_convertidos_com_cep__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/novos-convertidos/{convertido_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter Novo Convertido
         * @description Obtém um novo convertido pelo ID.
         */
        get: operations["obter_novo_convertido_novos_convertidos__convertido_id__get"];
        /**
         * Atualizar Novo Convertido
         * @description Atualiza um novo convertido.
         */
        put: operations["atualizar_novo_convertido_novos_convertidos__convertido_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discipulador/{discipulador_id}/convertidos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar Convertidos Por Discipulador
         * @description Lista todos os novos convertidos de um discipulador.
         */
        get: operations["listar_convertidos_por_discipulador_discipulador__discipulador_id__convertidos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discipulador/convertidos/{convertido_id}/vincular/{discipulador_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Vincular Convertido Discipulador
         * @description Vincula um novo convertido a um discipulador.
         */
        post: operations["vincular_convertido_discipulador_discipulador_convertidos__convertido_id__vincular__discipulador_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discipulador/convertidos/{convertido_id}/desvincular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Desvincular Convertido Discipulador
         * @description Remove a vinculação de um convertido com seu discipulador.
         */
        post: operations["desvincular_convertido_discipulador_discipulador_convertidos__convertido_id__desvincular_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discipulador/convertidos/{convertido_id}/discipulador": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obter Discipulador Convertido
         * @description Obtém o discipulador (user) responsável por um convertido.
         */
        get: operations["obter_discipulador_convertido_discipulador_convertidos__convertido_id__discipulador_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cep/{cep}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar Cep
         * @description Recebe um CEP e retorna os dados do endereço via ViaCEP.
         *
         *     Args:
         *         cep: CEP a consultar (8 dígitos)
         *
         *     Returns:
         *         Dados do endereço (logradouro, bairro, cidade, uf, complemento)
         *
         *     Raises:
         *         HTTPException: Se CEP for inválido ou não encontrado
         */
        get: operations["buscar_cep_cep__cep__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contatos-novos-convertidos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Criar Contato */
        post: operations["criar_contato_contatos_novos_convertidos__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contatos-novos-convertidos-acoes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Acoes */
        get: operations["listar_acoes_contatos_novos_convertidos_acoes__get"];
        put?: never;
        /** Criar Acao Contato */
        post: operations["criar_acao_contato_contatos_novos_convertidos_acoes__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contatos-novos-convertidos-acoes/contato/{contato_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Acoes Contato */
        get: operations["listar_acoes_contato_contatos_novos_convertidos_acoes_contato__contato_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contatos-novos-convertidos-acoes/{acao_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Acao Contato */
        get: operations["obter_acao_contato_contatos_novos_convertidos_acoes__acao_id__get"];
        /** Atualizar Acao Contato */
        put: operations["atualizar_acao_contato_contatos_novos_convertidos_acoes__acao_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_auth_token_post */
        Body_login_auth_token_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** ContatoNovoConvertidoCreate */
        ContatoNovoConvertidoCreate: {
            /** Discipulador Id */
            discipulador_id: number;
            /** Novo Convertido Id */
            novo_convertido_id: number;
            /** Sucesso Contato */
            sucesso_contato: boolean;
            /**
             * Data Contato
             * Format: date
             */
            data_contato: string;
            /** Protocolo */
            protocolo?: string | null;
            /** Hora Protocolo */
            hora_protocolo?: string | null;
            /** Status Contato */
            status_contato?: string | null;
            /**
             * Confirmar Contato
             * @default false
             */
            confirmar_contato: boolean | null;
        };
        /** ContatoNovoConvertidoOut */
        ContatoNovoConvertidoOut: {
            /** Discipulador Id */
            discipulador_id: number;
            /** Novo Convertido Id */
            novo_convertido_id: number;
            /** Sucesso Contato */
            sucesso_contato: boolean;
            /**
             * Data Contato
             * Format: date
             */
            data_contato: string;
            /** Protocolo */
            protocolo?: string | null;
            /** Hora Protocolo */
            hora_protocolo?: string | null;
            /** Status Contato */
            status_contato?: string | null;
            /** Id */
            id: number;
        };
        /** ContatoNovosConvertidosAcoesCreate */
        ContatoNovosConvertidosAcoesCreate: {
            /** Contato Novo Convertido Id */
            contato_novo_convertido_id: number;
            /** Convite Culto Igreja */
            convite_culto_igreja: boolean;
            /** Convite Culto Lar */
            convite_culto_lar: boolean;
            /** Convite Escola Dominicial */
            convite_escola_dominicial: boolean;
            /** Convite Reuniao Discipulado */
            convite_reuniao_discipulado: boolean;
            /** Teleoracao */
            teleoracao: boolean;
            /** Outros Especificar */
            outros_especificar: boolean;
            /** Especificacao Outros */
            especificacao_outros?: string | null;
            /** Convite Culto Igreja Resposta */
            convite_culto_igreja_resposta: boolean;
            /** Convite Culto Lar Resposta */
            convite_culto_lar_resposta: boolean;
            /** Convite Escola Dominicial Resposta */
            convite_escola_dominicial_resposta: boolean;
            /** Convite Reuniao Discipulado Resposta */
            convite_reuniao_discipulado_resposta: boolean;
            /** Outros Especificar Resposta */
            outros_especificar_resposta: boolean;
            /** Especificacao Outros Resposta */
            especificacao_outros_resposta: string | null;
            /** Manter Contato */
            manter_contato: boolean;
            /** Motivo Nao Manter Contato */
            motivo_nao_manter_contato?: string | null;
            /** Candidato Abandonou Discipulado */
            candidato_abandonou_discipulado: boolean;
            /** Motivo Abandono Discipulado */
            motivo_abandono_discipulado?: string | null;
            /** Agendar Proximo Contato Data */
            agendar_proximo_contato_data?: string | null;
            /** Agendar Proximo Contato Hora */
            agendar_proximo_contato_hora?: string | null;
            /** Candidato Preparado Batismo */
            candidato_preparado_batismo: boolean;
            /** Data Batismo */
            data_batismo?: string | null;
            /** Candidato Esta Em Duvidas Batismo */
            candidato_esta_em_duvidas_batismo: boolean;
            /** Motivo Duvidas Batismo */
            motivo_duvidas_batismo?: string | null;
            /** Candidato Desistiu Batismo */
            candidato_desistiu_batismo: boolean;
            /** Motivo Desistencia Batismo */
            motivo_desistencia_batismo?: string | null;
        };
        /** ContatoNovosConvertidosAcoesOut */
        ContatoNovosConvertidosAcoesOut: {
            /** Contato Novo Convertido Id */
            contato_novo_convertido_id: number;
            /** Convite Culto Igreja */
            convite_culto_igreja: boolean;
            /** Convite Culto Lar */
            convite_culto_lar: boolean;
            /** Convite Escola Dominicial */
            convite_escola_dominicial: boolean;
            /** Convite Reuniao Discipulado */
            convite_reuniao_discipulado: boolean;
            /** Teleoracao */
            teleoracao: boolean;
            /** Outros Especificar */
            outros_especificar: boolean;
            /** Especificacao Outros */
            especificacao_outros?: string | null;
            /** Convite Culto Igreja Resposta */
            convite_culto_igreja_resposta: boolean;
            /** Convite Culto Lar Resposta */
            convite_culto_lar_resposta: boolean;
            /** Convite Escola Dominicial Resposta */
            convite_escola_dominicial_resposta: boolean;
            /** Convite Reuniao Discipulado Resposta */
            convite_reuniao_discipulado_resposta: boolean;
            /** Outros Especificar Resposta */
            outros_especificar_resposta: boolean;
            /** Especificacao Outros Resposta */
            especificacao_outros_resposta: string | null;
            /** Manter Contato */
            manter_contato: boolean;
            /** Motivo Nao Manter Contato */
            motivo_nao_manter_contato?: string | null;
            /** Candidato Abandonou Discipulado */
            candidato_abandonou_discipulado: boolean;
            /** Motivo Abandono Discipulado */
            motivo_abandono_discipulado?: string | null;
            /** Agendar Proximo Contato Data */
            agendar_proximo_contato_data?: string | null;
            /** Agendar Proximo Contato Hora */
            agendar_proximo_contato_hora?: string | null;
            /** Candidato Preparado Batismo */
            candidato_preparado_batismo: boolean;
            /** Data Batismo */
            data_batismo?: string | null;
            /** Candidato Esta Em Duvidas Batismo */
            candidato_esta_em_duvidas_batismo: boolean;
            /** Motivo Duvidas Batismo */
            motivo_duvidas_batismo?: string | null;
            /** Candidato Desistiu Batismo */
            candidato_desistiu_batismo: boolean;
            /** Motivo Desistencia Batismo */
            motivo_desistencia_batismo?: string | null;
            /** Id */
            id: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NovoConvertidoCreate */
        NovoConvertidoCreate: {
            /** Nome */
            nome: string;
            /** Telefone */
            telefone: string;
            /** Cep */
            cep: string;
            /** Endereco */
            endereco: string;
            /** Complemento */
            complemento?: string | null;
            /** Cidade */
            cidade: string;
            /** Bairro */
            bairro: string;
            /** Uf */
            uf: string;
            /**
             * Data Nascimento
             * Format: date
             */
            data_nascimento: string;
            /** Idade */
            idade?: number | null;
            /**
             * Data Conversao
             * Format: date
             */
            data_conversao: string;
            /** Discipulador Id */
            discipulador_id: number;
        };
        /** NovoConvertidoOut */
        NovoConvertidoOut: {
            /** Nome */
            nome: string;
            /** Telefone */
            telefone: string;
            /** Cep */
            cep: string;
            /** Endereco */
            endereco: string;
            /** Complemento */
            complemento?: string | null;
            /** Cidade */
            cidade: string;
            /** Bairro */
            bairro: string;
            /** Uf */
            uf: string;
            /**
             * Data Nascimento
             * Format: date
             */
            data_nascimento: string;
            /** Idade */
            idade: number | null;
            /**
             * Data Conversao
             * Format: date
             */
            data_conversao: string;
            /** Discipulador Id */
            discipulador_id: number;
            /** Id */
            id: number;
            /**
             * Data Cadastro
             * Format: date
             */
            data_cadastro: string;
        };
        /**
         * NovoConvertidoUpdate
         * @description Modelo para atualização — todos os campos opcionais.
         */
        NovoConvertidoUpdate: {
            /** Nome */
            nome?: string | null;
            /** Telefone */
            telefone?: string | null;
            /** Cep */
            cep?: string | null;
            /** Endereco */
            endereco?: string | null;
            /** Complemento */
            complemento?: string | null;
            /** Cidade */
            cidade?: string | null;
            /** Bairro */
            bairro?: string | null;
            /** Uf */
            uf?: string | null;
            /** Data Nascimento */
            data_nascimento?: string | null;
            /** Idade */
            idade?: number | null;
            /** Data Conversao */
            data_conversao?: string | null;
            /** Discipulador Id */
            discipulador_id?: number | null;
        };
        /** UserCreate */
        UserCreate: {
            /** Nome */
            nome: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Telefone */
            telefone?: string | null;
            /** Password */
            password: string;
        };
        /** UserOut */
        UserOut: {
            /** Nome */
            nome: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Telefone */
            telefone?: string | null;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Nome */
            nome?: string | null;
            /** Telefone */
            telefone?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listar_usuarios_users__get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_usuario_users__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_usuario_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    atualizar_usuario_users__user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    contar_convertidos_discipulador_users__user_id__convertidos_count_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_novos_convertidos_novos_convertidos__get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NovoConvertidoOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_novo_convertido_novos_convertidos__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NovoConvertidoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NovoConvertidoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_novo_convertido_com_cep_novos_convertidos_com_cep__post: {
        parameters: {
            query: {
                /** @description CEP para preenchimento automático */
                cep: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NovoConvertidoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NovoConvertidoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_novo_convertido_novos_convertidos__convertido_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                convertido_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NovoConvertidoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    atualizar_novo_convertido_novos_convertidos__convertido_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                convertido_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NovoConvertidoUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NovoConvertidoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_convertidos_por_discipulador_discipulador__discipulador_id__convertidos_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path: {
                discipulador_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NovoConvertidoOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    vincular_convertido_discipulador_discipulador_convertidos__convertido_id__vincular__discipulador_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                convertido_id: number;
                discipulador_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NovoConvertidoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    desvincular_convertido_discipulador_discipulador_convertidos__convertido_id__desvincular_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                convertido_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NovoConvertidoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_discipulador_convertido_discipulador_convertidos__convertido_id__discipulador_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                convertido_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    buscar_cep_cep__cep__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cep: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    criar_contato_contatos_novos_convertidos__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContatoNovoConvertidoCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContatoNovoConvertidoOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_acoes_contatos_novos_convertidos_acoes__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContatoNovosConvertidosAcoesOut"][];
                };
            };
        };
    };
    criar_acao_contato_contatos_novos_convertidos_acoes__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContatoNovosConvertidosAcoesCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContatoNovosConvertidosAcoesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_acoes_contato_contatos_novos_convertidos_acoes_contato__contato_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                contato_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContatoNovosConvertidosAcoesOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_acao_contato_contatos_novos_convertidos_acoes__acao_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                acao_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContatoNovosConvertidosAcoesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    atualizar_acao_contato_contatos_novos_convertidos_acoes__acao_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                acao_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContatoNovosConvertidosAcoesCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContatoNovosConvertidosAcoesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
